### ISSUE TITLE
Error starting td-agent

### ISSUE THREAD

**Issue by amgmdz** [senvardarsemih/fluent-logging-demo#1]
I have used its td-agent.conf and when restarting the service it gives the following error: config error file="/etc/td-agent/td-agent.conf" error="'format' parameter is required". 

[td-agent.conf](https://github.com/senvardarsemih/fluent-logging-demo/blob/main/configs/td-agent/td-agent.conf)

**Comment by amgmdz** [comment]
I think I was able to solve it by replacing:

```
<filter *.**>
  @type parser
  key_name log
  reserve_data true
  format json #fix error
  remove_key_name_field true
  emit_invalid_record_to_error false
  #<parse>
  #  @type json
  #</parse>
</filter>
```

**Comment by senvardarsemih** [comment]
@amgmdz  I'm glad you're resolving your problem.
The **type** parameter specifies the type of the plugin. The parser filter plugin "parses" string field in event records and mutates its event record with the parsed result. You can check the documentation from [here](https://docs.fluentd.org/filter/parser)
